settings:
  randomAlt: false
  quantum: false
  alt400OnFailedRequestValidation: true
routes:
- group: default
  type: REST
  method: GET
  path: /jwt
  alt: ""
  responseCode: 200
  response: "{\n  \"sub\": \"${sub:DEFAULT}\",\n  \"name\": \"${name:DEFAULT}\",\n  \"iat\": ${iat:0}\n}"
  requestBodySchema: ""
  disabled: false
- group: entity
  type: REST
  method: GET
  path: /api/v2/entity
  alt: ""
  responseCode: 200
  response: "[\n  {\"id\": ${sequence}, \"name\": \"${random_string}\"},\n  {\"id\": ${sequence}, \"name\": \"${enum:Java:C++:Python:JavaScript}\"},\n  {\"id\": ${sequence}, \"name\": \"${enum:Java:C++:Python:JavaScript}\"},\n  {\"id\": ${sequence}, \"name\": \"${lang:${enum:Java:C++:Python:JavaScript}}\"}\n]"
  requestBodySchema: ""
  disabled: false
- group: entity
  type: REST
  method: GET
  path: /api/v2/entity
  alt: 400
  responseCode: 400
  response: "[]"
  requestBodySchema: ""
  disabled: false
- group: entity
  type: REST
  method: GET
  path: "/api/v2/entity/{id}"
  alt: ""
  responseCode: 200
  response: "{\"id\": ${id}, \"name\": \"entity name\"}"
  requestBodySchema: ""
  disabled: true
- group: entity
  type: REST
  method: PUT
  path: /api/v2/entity
  alt: ""
  responseCode: 201
  response: "{\"id\": ${random_int}, \"name\": \"${name:default name}\"}"
  requestBodySchema: ""
  disabled: false
- group: entity
  type: REST
  method: DELETE
  path: "/api/v2/entity/{id}"
  alt: ""
  responseCode: 200
  response: "{\"id\": ${random_int}, \"name\": \"${name:default name}\"}"
  requestBodySchema: ""
  disabled: false
- group: number conversion
  type: SOAP
  method: POST
  path: /mockNumberConversion
  alt: ""
  responseCode: 200
  response: "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:web=\"http://www.dataaccess.com/webservicesserver/\">\n  <soapenv:Header/>\n  <soapenv:Body>\n    <web:NumberToDollarsResponse>\n      <web:NumberToDollarsResult>${enum:TEST1:TEST2}</web:NumberToDollarsResult>\n      <web:Result>${NumberToDollarsRequest.Value:DEFAULT_VALUE}</web:Result>\n    </web:NumberToDollarsResponse>\n  </soapenv:Body>\n</soapenv:Envelope>"
  requestBodySchema: ""
  disabled: false
- group: robot
  type: REST
  method: GET
  path: /api/robot
  alt: ""
  responseCode: 202
  response: "HTTP/1.1\nExtra: extra-value\n\n{\"name\": \"Johnny 5\"}\n---\nGET http://localhost:8081/api/robot HTTP/1.1\nMock-Alt: api-robot/R2D2\n\n{}"
  requestBodySchema: ""
  disabled: false
- group: robot
  type: REST
  method: GET
  path: /api/robot
  alt: R2D2
  responseCode: 200
  response: "{\"name\": \"R2D2\"}"
  requestBodySchema: ""
  disabled: false
- group: robot
  type: REST
  method: GET
  path: /api/robot
  alt: terminator
  responseCode: 200
  response: "{\"name\": \"terminator\"}"
  requestBodySchema: ""
  disabled: false
- group: store
  type: REST
  method: POST
  path: /v2/store/order
  alt: ""
  responseCode: 200
  response: "{\n    \"id\": 9585378182,\n    \"petId\": 793835,\n    \"quantity\": 79463074,\n    \"shipDate\": \"2018-11-13T20:20:39+00:00\",\n    \"status\": \"placed\",\n    \"complete\": true\n}"
  requestBodySchema: "{\r\n  \"type\" : \"object\",\r\n  \"properties\" : {\r\n    \"id\" : {\r\n      \"type\" : \"integer\",\r\n      \"format\" : \"int64\"\r\n    },\r\n    \"petId\" : {\r\n      \"type\" : \"integer\",\r\n      \"format\" : \"int64\"\r\n    },\r\n    \"quantity\" : {\r\n      \"type\" : \"integer\",\r\n      \"format\" : \"int32\"\r\n    },\r\n    \"shipDate\" : {\r\n      \"type\" : \"string\",\r\n      \"format\" : \"date-time\"\r\n    },\r\n    \"status\" : {\r\n      \"type\" : \"string\",\r\n      \"description\" : \"Order Status\",\r\n      \"enum\" : [ \"placed\", \"approved\", \"delivered\" ]\r\n    },\r\n    \"complete\" : {\r\n      \"type\" : \"boolean\",\r\n      \"default\" : false\r\n    }\r\n  }\r\n}"
  disabled: false
- group: store
  type: REST
  method: POST
  path: /v2/store/order
  alt: 400
  responseCode: 400
  response: "{\n    \"id\": 9585378182,\n    \"petId\": 793835,\n    \"quantity\": 79463074,\n    \"shipDate\": \"2018-11-13T20:20:39+00:00\",\n    \"status\": \"placed\",\n    \"complete\": true,\n    \"errorMessage\": \"${requestBodyValidationErrorMessage:}\"\n}"
  requestBodySchema: ""
  disabled: false
scenarios:
- group: default
  alias: New Alias 1
  type: MAP
  data: ""
- group: default
  alias: New Alias 2
  type: MAP
  data: ""
- group: entity
  alias: entity 400
  type: MAP
  data: GET;/api/v2/entity;400
- group: entity
  alias: entity alt 400
  type: CIRCULAR_QUEUE
  data: |-
    GET;/api/v2/entity
    GET;/api/v2/entity;400
- group: robot
  alias: robot sequence
  type: QUEUE
  data: |-
    GET;/api/robot;R2D2
    GET;/api/robot;
    GET;/api/robot;terminator
