server:
  port: 8081

logging:
  level:
    ROOT: ${ROOT_LOGGING_LEVEL:INFO}
    com.mockservice: ${LOGGING_LEVEL:INFO}
    org.springframework.boot.SpringApplication: INFO

spring:
  application:
    name: MockService

  main:
    banner-mode: LOG

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/webapp/
    suffix: .html

application:
  config: ${CONFIG_FILE:.\config.yml}
  config-backup: ${CONFIG_BACKUP_FILE:.\config-backup.yml}
  soap-error-data-file: soapFault.xml
  cache:
    response: 256
