server:
  port: 8081

logging:
  level:
    ROOT: ${LOGGING_LEVEL:INFO}

spring:
  application:
    name: MockService

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/webapp/
    suffix: .html

application:
  config:
    default-path: classpath:defaultConfig.yml
    path: .\config.yml
  soap-error-data-file: soapFault.xml
  cache:
    rest-resource: 256
    soap-resource: 256
