server:
  port: 8081

logging:
  level:
    ROOT: ${ROOT_LOGGING_LEVEL:INFO}
    com.mockservice: ${LOGGING_LEVEL:INFO}

spring:
  application:
    name: MockService

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/webapp/
    suffix: .html

application:
  config: ${CONFIG_FILE:.\config.yml}
  soap-error-data-file: soapFault.xml
  cache:
    response: 256
