server:
  port: 8081

logging:
  level:
    ROOT: ${ROOT_LOGGING_LEVEL:INFO}
    com.mockservice: ${LOGGING_LEVEL:INFO}
    org.springframework.boot.SpringApplication: INFO

spring:
  application:
    name: MockService

  main:
    banner-mode: LOG

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/webapp/
    suffix: .html

application:
  config-filename: ${CONFIG_FILENAME:.\config.yml}
  config-backup-filename: ${CONFIG_BACKUP_FILENAME:.\config-backup.yml}
  soap-error-data-file: soapFault.xml
  cache:
    response: 256
  request-service:
    initial-delay: 10000
    fixed-delay: 5000
