server:
  port: 8081

logging:
  level:
    ROOT: ${LOGGING_LEVEL:INFO}

spring:
  application:
    name: MockService

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/webapp/
    suffix: .html

application:
  config-path: classpath:data/config.yml
  cache:
    rest-mock-resource: 256
    soap-mock-resource: 256
