routes:
- group: Example Rest Service
  path: /api/v2/entity
  method: GET
  type: REST
  suffix: null
  response: |-
    [
      {"id": ${sequence}, "name": "${random_string}"},
      {"id": ${sequence}, "name": "${of:Java:C++:Python:JavaScript}"},
      {"id": ${sequence}, "name": "${of:Java:C++:Python:JavaScript}"},
      {"id": ${sequence}, "name": "${of:Java:C++:Python:JavaScript}"}
    ]
  disabled: false
- group: Example Rest Service
  path: /api/v2/entity
  method: GET
  type: REST
  suffix: error
  response: |-
    HTTP/1.1 400

    []
  disabled: false
- group: Example Rest Service
  path: /api/v2/entity/{id}
  method: GET
  type: REST
  suffix: null
  response: |-
    {"id": ${id}, "name": "entity name"}
  disabled: false
- group: Example Rest Service
  path: /api/v2/entity/filter
  method: GET
  type: REST
  suffix: null
  response: |-
    [
      {"id": 2, "name": "${a:default a}"},
      {"id": 3, "name": "${b:${of:default B1:default B2:default B3}}"}
    ]
  disabled: false
- group: Example Rest Service
  path: /api/v2/entity
  method: POST
  type: REST
  suffix: null
  response: |-
    HTTP/1.1 201
    Custom-Header: entity-created

    {"id": ${random_int}, "name": "${name}"}
  disabled: false
- group: Example Soap Service
  path: /mockNumberConversion2
  method: POST
  type: SOAP
  suffix: null
  response: |-
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.dataaccess.com/webservicesserver/">
      <soapenv:Header/>
      <soapenv:Body>
        <web:NumberToDollarsResponse>
          <web:NumberToDollarsResult>${random_string_of:TEST1:TEST2}</web:NumberToDollarsResult>
        </web:NumberToDollarsResponse>
      </soapenv:Body>
    </soapenv:Envelope>
  disabled: false